- hosts: localhost
  become: true
  vars_files:
    - ./azure_ansible_vars.yml
  tasks:
    - name: install strongswan
      apt: name=strongswan update_cache=yes
    - name: install strongswan-pki
      apt: name=strongswan-pki update_cache=yes
    - name: echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        line: net.ipv4.ip_forward=1
    - name: echo "net.ipv4.conf.all.accept_redirects=0" >> /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        line: net.ipv4.conf.all.accept_redirects=0
    - name: echo "net.ipv4.conf.all.send_redirects=0" >> /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        line: net.ipv4.conf.all.send_redirects=0
    - name: echo "net/ipv4/ip_no_pmtu_disc=1" >> /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        line: net/ipv4/ip_no_pmtu_disc=1
    - name: sysctl -p /etc/sysctl.conf
      command: sysctl -p /etc/sysctl.conf
    - name: create /etc/ipsec.secrets
      copy:
        dest: "/etc/ipsec.secrets"
        content: |
          @aws @azure : PSK "secret"
    - name: create /etc/ipsec.conf
      copy:
        dest: "/etc/ipsec.conf"
        content: |
          config setup

          conn %default
              ikelifetime=60m
              keylife=20m
              rekeymargin=3m
              keyingtries=1
              authby=secret
              keyexchange=ikev2
              mobike=no

          conn net-net
              left={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}
              leftsubnet=172.31.64.0/24
              leftid=@aws
              leftfirewall=no
              right={{ azure_public_ip }}
              rightsubnet={{ azure_vpn_subnet}}
              rightid=@azure
              ike=aes256-sha2_256-modp2048!
              esp=aes256-sha2_256!
              auto=start
    #- name: systemctl restart strongswan
    #  command: systemctl restart strongswan
    - name: ufw allow OpenSSH
      command: ufw allow OpenSSH
    - name: ufw allow 500,4500/udp
      command: ufw allow 500,4500/udp
    - name: insert before *filter
      blockinfile:
        dest: /etc/ufw/before.rules
        block: | 
          *nat
          -A POSTROUTING -s 10.0.1.0/24 -o eth0 -m policy --pol ipsec --dir out -j ACCEPT
          -A POSTROUTING -s 10.0.1.0/24 -o eth0 -j MASQUERADE
          COMMIT

          *mangle
          -A FORWARD --match policy --pol ipsec --dir in -s 10.0.1.0/24 -o eth0 -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1361:1536 -j TCPMSS --set-mss 1360
          COMMIT
        insertbefore: ".*filter"
    - name: insert after :ufw-not-local - [0:0]
      lineinfile:
        path: /etc/ufw/before.rules
        line: "-A ufw-before-forward --match policy --pol ipsec --dir in --proto esp -s 10.0.1.0/24 -j ACCEPT"
        insertbefore: "# End required lines"
    - name: insert after :ufw-not-local - [0:0]
      lineinfile:
        path: /etc/ufw/before.rules
        line: "-A ufw-before-forward --match policy --pol ipsec --dir out --proto esp -d 10.0.1.0/24 -j ACCEPT"
        insertbefore: "# End required lines"
    - name: ufw enable
      ufw:
        state: enabled
    - name: Change permissions of private key file
      file: 
        path: /home/ubuntu/.ssh/id_rsa
        mode: '0600'
    
