- hosts: all
  become: true
  vars_files:
    - ./ansible_vars.yml
  tasks:
    - name: install strongswan
      apt: name=strongswan update_cache=yes
    - name: install strongswan-pki
      apt: name=strongswan-pki update_cache=yes
    - name: echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        line: net.ipv4.ip_forward=1
    - name: echo "net.ipv4.conf.all.accept_redirects=0" >> /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        line: net.ipv4.conf.all.accept_redirects=0
    - name: echo "net.ipv4.conf.all.send_redirects=0" >> /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        line: net.ipv4.conf.all.send_redirects=0
    - name: sysctl -p /etc/sysctl.conf
      command: sysctl -p /etc/sysctl.conf
    - name: create /etc/ipsec.secrets
      copy:
        dest: "/etc/ipsec.secrets"
        content: |
          @aws @azure : PSK "secret"
    - name: create /etc/ipsec.conf
      copy:
        dest: "/etc/ipsec.conf"
        content: |
          config setup

          conn %default
              ikelifetime=60m
              keylife=20m
              rekeymargin=3m
              keyingtries=1
              authby=secret
              keyexchange=ikev2
              mobike=no

          conn net-net
              left={{ aws_public_ip }}
              leftsubnet=172.31.64.0/24
              leftid=@aws
              leftfirewall=no
              right={{ azure_public_ip }}
              rightsubnet=10.0.1.0/24
              rightid=@azure
              ike=aes256-sha2_256-modp2048!
              esp=aes256-sha2_256!
              auto=start
    - name: systemctl restart strongswan
      command: systemctl restart strongswan
