- hosts: all
  become: true

  tasks:
    - name: install strongswan
      apt: name=strongswan update_cache=yes
    - name: install strongswan-pki
      apt: name=strongswan-pki update_cache=yes
    - name: update kernel parameters
      blockinfile:
        path: /etc/sysctl.conf
        block: |
          net.ipv4.ip_forward = 1 
          net.ipv4.conf.all.accept_redirects = 0 
          net.ipv4.conf.all.send_redirects = 0
    - name: refresh kernel parameters
      command: sysctl -p
    - name: update ipsec.conf
      template:
        src: ipsec.j2
        dest: /etc/ipsec.conf
        backup: yes
    - name: update ipsec secrets
      copy:
        dest: /etc/ipsec.secrets
        content: |
          <source ip> <destination ip> : <secrettype>  <secret>
          left right: PSK 1245
      